# Generated by Django 5.2 on 2025-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ImageField(default='default_images.png', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='product_name', max_length=40),
        ),
    ]
