# Generated by Django 4.2.11 on 2025-05-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_images_item_price_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Nome Produto', max_length=40),
        ),
    ]
