# Generated by Django 5.2 on 2025-05-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, default='default_images.png', null=True, upload_to='product_images/'),
        ),
    ]
