# Generated by Django 4.2.11 on 2025-06-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_item_description_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.IntegerField(default=0),
        ),
    ]
