# Generated by Django 4.2.11 on 2025-07-23 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockmovement_user_alter_item_minimum_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 20, 55, tzinfo=datetime.timezone.utc)),
        ),
    ]
