# Generated by Django 4.2.11 on 2025-07-23 14:25

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_stockmovement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='data',
            field=models.DateTimeField(default=inventory.models.StockMovement.now_no_microseconds),
        ),
    ]
