# Generated by Django 4.2.11 on 2025-07-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockmovement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='quantidade_antes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
