# Generated by Django 4.2.11 on 2025-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockmovement_quantidade_antes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantidade_antes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
